login: &login
 adapter: mysql
 host: localhost
 username: root

development:
 <<: *login
 database: booking_dev

test:
 <<: *login 
 database: booking_test

production:
 <<: *login
 database: booking_prod
